import { writeFileSync, existsSync, mkdirSync } from "fs"
import { resolve, dirname } from "path"

const TOKEN = process.env.GITHUB_TOKEN
const USERNAME = "ssaahhil832"
const DATA_PATH = resolve(import.meta.dirname, "../src/data/github-data.ts")

const projectRepoMap = {
  "Quantum Job Tracker Dashboard": ["Quantum_Qiskit", "Quantum_projects"],
  "AI Student Inquiry Chatbot": ["college-chat-bot", "college-chat-bot-agent-liamaparse"],
  "Face Detection System": ["ML_Projects"],
  "EduCycle Project": ["market-place-workers"],
}

async function fetchAllRepos() {
  const headers = {
    Accept: "application/vnd.github+json",
    ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
  }

  const repos = []
  let page = 1
  let hasMore = true

  while (hasMore) {
    const res = await fetch(
      `https://api.github.com/users/${USERNAME}/repos?per_page=100&page=${page}&sort=updated`,
      { headers }
    )
    if (!res.ok) {
      console.error(`GitHub API error: ${res.status} ${res.statusText}`)
      process.exit(1)
    }
    const data = await res.json()
    if (data.length === 0) break
    repos.push(...data)
    page++
    if (data.length < 100) hasMore = false
  }

  return repos
}

function buildProjectMapping(repos) {
  const repoMap = {}
  for (const r of repos) {
    repoMap[r.name] = {
      name: r.name,
      description: r.description || "",
      stars: r.stargazers_count,
      language: r.language || "",
      url: r.html_url,
      updatedAt: r.pushed_at,
      forks: r.forks_count,
      isFork: r.fork,
    }
  }

  const mapped = {}
  for (const [project, repoList] of Object.entries(projectRepoMap)) {
    const matched = repoList
      .map((name) => repoMap[name])
      .filter(Boolean)
    if (matched.length > 0) {
      mapped[project] = matched
    }
  }

  return mapped
}

function reposWithoutProject(repos, mapping) {
  const mappedRepoNames = new Set(
    Object.values(projectRepoMap).flat()
  )
  return repos
    .filter((r) => !r.fork && r.name !== `${USERNAME}.github.io`)
    .filter((r) => !mappedRepoNames.has(r.name))
    .map((r) => ({
      name: r.name,
      description: r.description || "",
      stars: r.stargazers_count,
      language: r.language || "",
      url: r.html_url,
      updatedAt: r.pushed_at,
      forks: r.forks_count,
    }))
}

async function main() {
  console.log("Fetching repos for", USERNAME)
  const repos = await fetchAllRepos()
  console.log(`Found ${repos.length} repos`)

  const projectMapping = buildProjectMapping(repos)
  const otherRepos = reposWithoutProject(repos, projectMapping)

  const output = `// Auto-generated by scripts/fetch-github.mjs — do not edit manually
// Generated: ${new Date().toISOString()}

export interface GitHubRepo {
  name: string
  description: string
  stars: number
  language: string
  url: string
  updatedAt: string
  forks: number
  isFork?: boolean
}

export const githubProjectMapping: Record<string, GitHubRepo[]> = ${JSON.stringify(projectMapping, null, 2)} as const

export const githubOtherRepos: GitHubRepo[] = ${JSON.stringify(otherRepos, null, 2)} as const
`

  const dir = dirname(DATA_PATH)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
  writeFileSync(DATA_PATH, output, "utf-8")
  const mappedCount = Object.keys(projectMapping).length
  const repoCount = Object.values(projectMapping).flat().length
  console.log(`Written ${DATA_PATH}`)
  console.log(`Mapped ${mappedCount} projects → ${repoCount} repos`)
  console.log(`${otherRepos.length} additional repos listed`)
}

main().catch((err) => {
  console.error("Script failed:", err)
  process.exit(1)
})
