// Auto-generated by scripts/fetch-github.mjs — do not edit manually
// Generated: 2026-06-01T19:32:43.094Z

export interface GitHubRepo {
  name: string
  description: string
  stars: number
  language: string
  url: string
  updatedAt: string
  forks: number
  isFork?: boolean
}

export const githubProjectMapping: Record<string, GitHubRepo[]> = {
  "Quantum Job Tracker Dashboard": [
    {
      "name": "Quantum_Qiskit",
      "description": "",
      "stars": 0,
      "language": "Python",
      "url": "https://github.com/ssahilkhan/Quantum_Qiskit",
      "updatedAt": "2026-02-18T14:44:00Z",
      "forks": 0,
      "isFork": false
    },
    {
      "name": "Quantum_projects",
      "description": "",
      "stars": 0,
      "language": "Python",
      "url": "https://github.com/ssahilkhan/Quantum_projects",
      "updatedAt": "2026-01-03T05:41:50Z",
      "forks": 0,
      "isFork": false
    }
  ],
  "AI Student Inquiry Chatbot": [
    {
      "name": "college-chat-bot",
      "description": "",
      "stars": 0,
      "language": "Python",
      "url": "https://github.com/ssahilkhan/college-chat-bot",
      "updatedAt": "2026-05-23T11:56:07Z",
      "forks": 0,
      "isFork": false
    },
    {
      "name": "college-chat-bot-agent-liamaparse",
      "description": "",
      "stars": 0,
      "language": "Python",
      "url": "https://github.com/ssahilkhan/college-chat-bot-agent-liamaparse",
      "updatedAt": "2026-03-29T06:12:59Z",
      "forks": 0,
      "isFork": false
    }
  ],
  "Face Detection System": [
    {
      "name": "ML_Projects",
      "description": "",
      "stars": 0,
      "language": "Python",
      "url": "https://github.com/ssahilkhan/ML_Projects",
      "updatedAt": "2026-03-22T14:19:49Z",
      "forks": 0,
      "isFork": false
    }
  ],
  "EduCycle Project": [
    {
      "name": "market-place-workers",
      "description": "",
      "stars": 0,
      "language": "JavaScript",
      "url": "https://github.com/ssahilkhan/market-place-workers",
      "updatedAt": "2026-05-23T11:59:56Z",
      "forks": 0,
      "isFork": false
    }
  ]
} as const

export const githubOtherRepos: GitHubRepo[] = [
  {
    "name": "portfolio-2ojec",
    "description": "Futuristic multi-page personal portfolio - Sahil Khan",
    "stars": 0,
    "language": "TypeScript",
    "url": "https://github.com/ssahilkhan/portfolio-2ojec",
    "updatedAt": "2026-06-01T19:12:54Z",
    "forks": 0
  },
  {
    "name": "github-portfolio",
    "description": "",
    "stars": 0,
    "language": "TypeScript",
    "url": "https://github.com/ssahilkhan/github-portfolio",
    "updatedAt": "2026-05-23T12:35:37Z",
    "forks": 0
  },
  {
    "name": "superexpert-ai",
    "description": "",
    "stars": 0,
    "language": "TypeScript",
    "url": "https://github.com/ssahilkhan/superexpert-ai",
    "updatedAt": "2026-05-23T12:10:32Z",
    "forks": 0
  },
  {
    "name": "spam-detector",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/spam-detector",
    "updatedAt": "2026-05-23T12:09:40Z",
    "forks": 0
  },
  {
    "name": "projects-collection",
    "description": "",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/projects-collection",
    "updatedAt": "2026-05-23T12:08:29Z",
    "forks": 0
  },
  {
    "name": "practice-exercises",
    "description": "",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/practice-exercises",
    "updatedAt": "2026-05-23T12:06:48Z",
    "forks": 0
  },
  {
    "name": "personal-ai",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/personal-ai",
    "updatedAt": "2026-05-23T12:06:26Z",
    "forks": 0
  },
  {
    "name": "ollama-opencode-llm",
    "description": "",
    "stars": 0,
    "language": "CSS",
    "url": "https://github.com/ssahilkhan/ollama-opencode-llm",
    "updatedAt": "2026-05-23T12:02:54Z",
    "forks": 0
  },
  {
    "name": "ollama-projects",
    "description": "",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/ollama-projects",
    "updatedAt": "2026-05-23T12:02:34Z",
    "forks": 0
  },
  {
    "name": "love-app",
    "description": "",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/love-app",
    "updatedAt": "2026-05-23T12:01:54Z",
    "forks": 0
  },
  {
    "name": "expense-tracker-ai",
    "description": "",
    "stars": 0,
    "language": "Dart",
    "url": "https://github.com/ssahilkhan/expense-tracker-ai",
    "updatedAt": "2026-05-23T11:58:36Z",
    "forks": 0
  },
  {
    "name": "deepinfinity",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/deepinfinity",
    "updatedAt": "2026-05-23T11:57:59Z",
    "forks": 0
  },
  {
    "name": "voice-assistant-app",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/voice-assistant-app",
    "updatedAt": "2026-05-23T11:57:04Z",
    "forks": 0
  },
  {
    "name": "articles",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/articles",
    "updatedAt": "2026-05-23T11:55:37Z",
    "forks": 0
  },
  {
    "name": "article-web-page",
    "description": "",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/article-web-page",
    "updatedAt": "2026-05-23T11:55:09Z",
    "forks": 0
  },
  {
    "name": "rankwars",
    "description": "",
    "stars": 0,
    "language": "TypeScript",
    "url": "https://github.com/ssahilkhan/rankwars",
    "updatedAt": "2026-05-23T11:54:39Z",
    "forks": 0
  },
  {
    "name": "AI-Document-Reader",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/AI-Document-Reader",
    "updatedAt": "2026-05-23T11:53:43Z",
    "forks": 0
  },
  {
    "name": "ssaahhil832.github.io",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/ssaahhil832.github.io",
    "updatedAt": "2026-04-26T11:34:02Z",
    "forks": 0
  },
  {
    "name": "sahil-portfolio",
    "description": "My personal portfolio website",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/sahil-portfolio",
    "updatedAt": "2026-04-26T10:19:05Z",
    "forks": 0
  },
  {
    "name": "certifications",
    "description": "Certificates I have got",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/certifications",
    "updatedAt": "2026-04-15T04:30:06Z",
    "forks": 0
  },
  {
    "name": "cnslab",
    "description": "",
    "stars": 0,
    "language": "Java",
    "url": "https://github.com/ssahilkhan/cnslab",
    "updatedAt": "2026-04-07T03:22:45Z",
    "forks": 0
  },
  {
    "name": "secure-message-app",
    "description": "messaging application ",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/secure-message-app",
    "updatedAt": "2026-01-27T10:36:06Z",
    "forks": 0
  },
  {
    "name": "ML-Programs",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/ML-Programs",
    "updatedAt": "2026-01-04T09:01:26Z",
    "forks": 0
  },
  {
    "name": "MyResume",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/MyResume",
    "updatedAt": "2026-01-03T05:21:16Z",
    "forks": 0
  },
  {
    "name": "python",
    "description": "",
    "stars": 0,
    "language": "Python",
    "url": "https://github.com/ssahilkhan/python",
    "updatedAt": "2025-12-18T07:37:35Z",
    "forks": 0
  },
  {
    "name": "Ai_tools",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/Ai_tools",
    "updatedAt": "2025-07-25T15:31:04Z",
    "forks": 0
  },
  {
    "name": "To-do_list",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/To-do_list",
    "updatedAt": "2025-07-21T05:56:56Z",
    "forks": 0
  },
  {
    "name": "HealthWeb",
    "description": "",
    "stars": 1,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/HealthWeb",
    "updatedAt": "2025-05-23T07:01:14Z",
    "forks": 0
  },
  {
    "name": "NewEduBest",
    "description": "",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/NewEduBest",
    "updatedAt": "2025-06-09T03:51:08Z",
    "forks": 0
  },
  {
    "name": "bookstore",
    "description": "",
    "stars": 0,
    "language": "CSS",
    "url": "https://github.com/ssahilkhan/bookstore",
    "updatedAt": "2025-06-08T12:31:07Z",
    "forks": 0
  },
  {
    "name": "NewEduVersion",
    "description": "",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/NewEduVersion",
    "updatedAt": "2025-06-08T09:26:26Z",
    "forks": 0
  },
  {
    "name": "NextEdu",
    "description": "",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/NextEdu",
    "updatedAt": "2025-05-24T07:18:26Z",
    "forks": 0
  },
  {
    "name": "HealthCare",
    "description": "helping old people to contact in emergency situation and maintaining their regular medication ",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/HealthCare",
    "updatedAt": "2025-05-16T05:00:04Z",
    "forks": 0
  },
  {
    "name": "CareCompanion",
    "description": "many helpful resources are available for health maintenance",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/CareCompanion",
    "updatedAt": "2025-05-16T15:10:30Z",
    "forks": 0
  },
  {
    "name": "healthcare_for_old_people",
    "description": "",
    "stars": 0,
    "language": "JavaScript",
    "url": "https://github.com/ssahilkhan/healthcare_for_old_people",
    "updatedAt": "2025-05-16T14:21:41Z",
    "forks": 0
  },
  {
    "name": "ai-voiceover-chatbot",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/ai-voiceover-chatbot",
    "updatedAt": "2025-03-20T09:01:58Z",
    "forks": 0
  },
  {
    "name": "space-article",
    "description": "",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/space-article",
    "updatedAt": "2025-03-06T10:49:18Z",
    "forks": 0
  },
  {
    "name": "my-website",
    "description": "",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/my-website",
    "updatedAt": "2025-01-09T10:14:04Z",
    "forks": 0
  },
  {
    "name": "webApps-repo",
    "description": "simple structure of web App :home page, sign-in page  , welcome page",
    "stars": 0,
    "language": "HTML",
    "url": "https://github.com/ssahilkhan/webApps-repo",
    "updatedAt": "2024-12-02T14:40:34Z",
    "forks": 0
  },
  {
    "name": "ssaahhil832",
    "description": "Config files for my GitHub profile.",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/ssaahhil832",
    "updatedAt": "2024-12-02T14:04:51Z",
    "forks": 0
  },
  {
    "name": "java-programming",
    "description": "",
    "stars": 0,
    "language": "",
    "url": "https://github.com/ssahilkhan/java-programming",
    "updatedAt": "2024-11-08T17:42:29Z",
    "forks": 0
  }
] as const
